### ISSUE TITLE
No

### ISSUE THREAD

**Issue by elisaado** [tjarratt/iCanHazUserAgent#1]
```ruby
 require 'sinatra'
 
 get '/' do
     request.user_agent
 end
```

**Comment by tjarratt** [comment]
Hey Eli. This is a pretty interesting issue you opened.

* This project is over 5 years old, and is a standalone webapp (probably written against a version of node.js 6+ releases old)
* Your issue title is just the english word "no" - which is probably one of the least helpful messages ever
* Your entire issue body is an example of doing something in ruby, which is not even the language this project was written in

Would you be so kind as to tell me why you're wasting my time being passive aggressive on the internet ? What were you hoping to achieve ? Did you think I would be amazed by your programming skills and hire you ? 

You might be better served remembering the adage that if you have nothing nice to say, you may as well say nothing at all.

**Comment by elisaado** [comment]
Hey Tim.

> Hey Eli. This is a pretty interesting issue you opened.

I agree!
<br>

> * This project is over 5 years old, and is a standalone webapp (probably written against a version of node.js 6+ releases old)

That may be, but you still don't need to use Jade or multiple files to return a single string.
<br>

> * Your issue title is just the english word "no" - which is probably one of the least helpful messages ever

Haha yes, it was not really intented as anything.
<br>

> * Your entire issue body is an example of doing something in ruby, which is not even the language this project was written in

Here comes the NodeJS example!

```javascript
const express = require('express')
const app = express()

app.get('/', (req, res) => res.send(req.headers['user-agent']))

app.listen(3000, () => console.log('Started on port 3000'))
```
<br>
Or older javascript

```javascript
var express = require('express');
var app = express();

app.get('/', function (req, res) {
  return res.send(req.headers['user-agent']);
});

app.listen(3000, function () {
  return console.log('Started on port 3000');
});
```
<br>

> Would you be so kind as to tell me why you're wasting my time being passive aggressive on the internet ? What were you hoping to achieve ? Did you think I would be amazed by your programming skills and hire you ?

Woah there, chill bro. Neither wasting your time nor being passive aggressive were not my intentions, I just wanted to show how it would be done much shorter. (Without Jade, and more than 1 file)
<br>

> You might be better served remembering the adage that if you have nothing nice to say, you may as well say nothing at all.

That doesn't seem healthy, if you hear nice things you can never improve anything. And again, my intent was not to be not nice.

**Comment by elisaado** [comment]
But this is an argument I can not win, I should have brought my criticism in a nicer way.
